apiVersion: v1
kind: Secret
metadata:
  name: santiago-clue
  namespace: treasure-hunt
type: Opaque
data:
  CLUE: Q0xVRS1BOiBtZXJlcXV0ZW5ndWUxMjM0IHwgVGlwOiBUZWFtIHVwIGFuZCBjb21iaW5lIGFsbCBjbHVlcy4= # echo -n 'CLUE-A: "merequtengue1234"\n' | base64 -w0
